name: Deploy Next js App

on:
 push:
   branches: [ main ]

jobs:
 build:
  runs-on: ubuntu-latest

  concurrency:
   group: deploy     
   cancel-in-progress: true        #if you commit three code at time it will build one time which will be third means latest

  steps:
   - name: Checkout Repository
     uses: actions/checkout@v6.0.1
   - name: Install Depdencies
     run: npm ci
   - name: Build Next.js App
     run: npm run build
   - name: Deploy App
     run: echo "Deploying App...."
   
